name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
    steps:
      - uses: actions/checkout@v4

      - name: Checkout ECommons
        uses: actions/checkout@v4
        with:
          repository: NightmareXIV/ECommons
          path: ECommons

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Download Dalamud
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -O /tmp/dalamud.zip
          unzip /tmp/dalamud.zip -d ${{ env.DALAMUD_HOME }}

      - name: Build
        run: dotnet build XelsCombatAI/XelsCombatAI.csproj -c Release
